### PR TITLE
Fix Azure support for Delta Sharing Server

### LINKED ISSUE #21: Support Azure Storage in Delta Sharing Server
Azure supports [shared access signature](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature) which is similar to signed url in other storage systems. It's not hard to make Delta Sharing Server support it.

### PR DESCRIPTION
**Pull request by zsxwing**
This is a followup PR for #56. There are multiple changes:

- Add integration tests for Azure.
- Change the pre-signed url generation for Azure to make sure it's scoped down to the path only. We also have tests verifying this.
- Refactor the code to leverage hadoop-azure to get credentials rather than from the system env. The user can just follow the hadoop-azure doc to set up the credentials. See the updated README for more information.

Closes #21

### CODE REVIEW

File: python/dev/lint-python [hunk 1]
```diff
@@ -246,7 +246,7 @@ function black_test {
     fi
 
     echo "starting black test..."
-    BLACK_REPORT=$( ($BLACK_BUILD delta_sharing --line-length 100 --check ) 2>&1)
+    BLACK_REPORT=$( ($BLACK_BUILD delta_sharing --line-length 100 --check --diff) 2>&1)
```
Comment (zsxwing) [inline python/dev/lint-python:249]: Update this to show the style details in CI

**Comment by zsxwing** [comment]
cc @goodwillpunning

File: server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala [hunk 2]
```diff
@@ -39,53 +44,147 @@ class S3FileSigner(
...
+    sharedAccessPolicy.setPermissions(java.util.EnumSet.of(SharedAccessBlobPermissions.READ))
+    sharedAccessPolicy.setSharedAccessExpiryTime(expiration)
+    sharedAccessPolicy
+  }
+
+  override def sign(path: Path): String = {
+    val containerRef = blobClient.getContainerReference(container)
+    val objectKey = objectKeyExtractor(path)
+    assert(objectKey.nonEmpty, s"cannot get object key from $path")
+    val blobRef = containerRef.getBlockBlobReference(objectKeyExtractor(path))
```
Comment (zhuansunxt) [inline server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala:103]: You can use `objectKey` here.

**Review by FX196 — APPROVED** [review]
